<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.0.309
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Apply Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'taesungju@gmail.com',
		'to' => 'taesungju@gmail.com'
	),
	'fields' => array(
		'custom_U614' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Applicant Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Applicant Name\' is required.'
			)
		),
		'custom_U585' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'School Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'School Name\' is required.'
			)
		),
		'custom_U598' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Reason',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Reason\' is required.'
			)
		),
		'custom_U666' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Contact Number / Cell Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Contact Number / Cell Phone\' is required.'
			)
		),
		'custom_U718' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Applicant Title/Position',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Applicant Title/Position\' is required.'
			)
		),
		'custom_U726' => array(
			'order' => 5,
			'type' => 'checkboxgroup',
			'label' => 'Subject',
			'required' => true,
			'optionItems' => array(
				'Mathematics',
				'Science(Biology/Physics/Chemistry',
				'ICT',
				'Korean Language'
			),
			'errors' => array(
				'required' => 'Field \'Subject\' is required.',
				'format' => 'Field \'Subject\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
